name: Cloudsmith OIDC Authentication

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # OIDC ke liye zaroori hai
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate OIDC Token
        run: |
          echo "Requesting OIDC Token..."
          
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/rini-jain")

          echo "Raw Token Response: $value"

          token=$(echo $value | jq '.value')

          echo "Extracted Token: $token"

          token_final=$(curl -X POST -H "Content-Type: application/json" \
          -d "{\"oidc_token\":$token, \"service_slug\":\"github-actions-oidc\"}" \
          https://api.cloudsmith.io/openid/rini-jain-RNYE/)

          echo "Cloudsmith Response: $token_final"

          final_api_token=$(echo $token_final | jq -r '.token')

          echo "Final Cloudsmith API Token: $final_api_token"

          echo "CLOUDSMITH_API_KEY=$final_api_token" >> $GITHUB_ENV


      - name: Push Package to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "raw"
          owner: "rini-jain-RNYE"  
          repo: "cloudsmith-gha-setup"  
          file: "./my-package.zip"
          republish: "true"
      - name: Debug Cloudsmith Inputs
        run: |
          echo "Cloudsmith API Key: $CLOUDSMITH_API_KEY"
          echo "Format: raw"
          echo "Owner: rini-jain-RNYE"
          echo "Repo: cloudsmith-gha-setup"
          echo "File: ./my-package.zip"
