name: Cloudsmith OIDC Authentication (NPM Package)

on:
  push:
    branches:
      - main

permissions:
  id-token: write  
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install Dependencies
        run: |
          cd npm-package
          npm install  

      - name: Build NPM Package (Generate .tgz)
        run: |
          cd npm-package
          npm pack 
          ls -l
      - name: Generate OIDC Token
        run: |
          echo "Requesting OIDC Token..."
          
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/rini-jain")

          token=$(echo $value | jq '.value')

          token_final=$(curl -X POST -H "Content-Type: application/json" \
          -d "{\"oidc_token\":$token, \"service_slug\":\"github-actions-oidc\"}" \
          https://api.cloudsmith.io/openid/rini-jain-RNYE/)

          final_api_token=$(echo $token_final | jq -r '.token')
          echo "CLOUDSMITH_API_KEY=$final_api_token" >> $GITHUB_ENV

      - name: Push NPM Package to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "npm"
          owner: "rini-jain-RNYE"  
          repo: "cloudsmith-gha-setup"  
          file: "$(ls npm-package/*.tgz)"  # This ensures the latest .tgz file is picked
          republish: "true"

      - name: Debug Cloudsmith API Call
        run: |
          echo "Checking Cloudsmith Repository Access..."
          curl -X GET "https://api.cloudsmith.io/v1/repos/rini-jain-RNYE/cloudsmith-gha-setup/" \
          -H "Authorization: Bearer $CLOUDSMITH_API_KEY"
