name: Cloudsmith OIDC Authentication

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # OIDC ke liye zaroori hai
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate OIDC Token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/rini-jain" | jq '.value')

          token=$(curl -X POST -H "Content-Type: application/json" \
          -d "{\"oidc_token\":$value, \"service_slug\":\"github-actions-oidc\"}" \
          https://api.cloudsmith.io/openid/rini-jain-RNYE/ | jq -r '.token')

          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Push Package to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "raw"
          owner: "rini-jain-RNYE"  
          repo: "cloudsmith-gha-setup"  
          file: "sample-package.zip"
          republish: "true"
